!> This module contains interstitial schemes that are specific to MMM physics.
module mmm_physics_compat
    use ccpp_kinds, only: kind_phys

    implicit none

    private
    public :: mmm_physics_accumulate_tendencies_timestep_init
    public :: mmm_physics_accumulate_tendencies_run
    public :: geopotential_height_wrt_sfc_to_msl_run
    public :: reverse
contains
    !> \section arg_table_mmm_physics_accumulate_tendencies_timestep_init Argument Table
    !! \htmlinclude mmm_physics_accumulate_tendencies_timestep_init.html
    pure subroutine mmm_physics_accumulate_tendencies_timestep_init( &
            dudt, dvdt, &
            rublten, rvblten, &
            errmsg, errflg)
        real(kind_phys), intent(out) :: dudt(:, :), dvdt(:, :)
        real(kind_phys), intent(out) :: rublten(:, :), rvblten(:, :)
        character(*), intent(out) :: errmsg
        integer, intent(out) :: errflg

        errmsg = ''
        errflg = 0

        ! Zero out tendencies at the beginning of each time step.

        ! Tendencies for feeding back to CAM-SIMA.
        dudt(:, :) = 0.0_kind_phys
        dvdt(:, :) = 0.0_kind_phys

        ! Tendencies generated by MMM physics.
        rublten(:, :) = 0.0_kind_phys
        rvblten(:, :) = 0.0_kind_phys
    end subroutine mmm_physics_accumulate_tendencies_timestep_init

    !> \section arg_table_mmm_physics_accumulate_tendencies_run Argument Table
    !! \htmlinclude mmm_physics_accumulate_tendencies_run.html
    pure subroutine mmm_physics_accumulate_tendencies_run( &
            dudt, dvdt, &
            rublten, rvblten, &
            errmsg, errflg)
        real(kind_phys), intent(inout) :: dudt(:, :), dvdt(:, :)
        real(kind_phys), intent(inout) :: rublten(:, :), rvblten(:, :)
        character(*), intent(out) :: errmsg
        integer, intent(out) :: errflg

        errmsg = ''
        errflg = 0

        ! Accumulate tendencies for feeding back to CAM-SIMA.
        dudt(:, :) = dudt(:, :) + rublten(:, :)
        dvdt(:, :) = dvdt(:, :) + rvblten(:, :)

        ! After the accumulation, zero out tendencies generated by MMM physics so that this subroutine is idempotent.
        rublten(:, :) = 0.0_kind_phys
        rvblten(:, :) = 0.0_kind_phys
    end subroutine mmm_physics_accumulate_tendencies_run

    !> \section arg_table_geopotential_height_wrt_sfc_to_msl_run Argument Table
    !! \htmlinclude geopotential_height_wrt_sfc_to_msl_run.html
    pure subroutine geopotential_height_wrt_sfc_to_msl_run( &
            pver, &
            gravit, phis, zmsfc, &
            zmmsl, &
            errmsg, errflg)
        integer, intent(in) :: pver
        real(kind_phys), intent(in) :: gravit, phis(:), zmsfc(:, :)
        real(kind_phys), intent(out) :: zmmsl(:, :)
        character(*), intent(out) :: errmsg
        integer, intent(out) :: errflg

        integer :: k

        errmsg = ''
        errflg = 0

        ! Convert geopotential height wrt surface to geopotential height wrt mean sea level, in accordance with
        ! its normal definition.
        do k = 1, pver
            zmmsl(:, k) = phis(:) / gravit + zmsfc(:, k)
        end do
    end subroutine geopotential_height_wrt_sfc_to_msl_run

    !> Helper function for reversing the order of elements in `array`.
    pure function reverse(array)
        real(kind_phys), intent(in) :: array(:)
        real(kind_phys) :: reverse(size(array))

        integer :: n

        n = size(array)

        ! There is nothing to reverse.
        if (n == 0) then
            return
        end if

        reverse(:) = array(n:1:-1)
    end function reverse
end module mmm_physics_compat
