!> This module contains interstitial schemes that are specific to MMM physics.
module mmm_physics_compat
    implicit none

    private
    public :: mmm_physics_compat_init
    public :: mmm_physics_compat_timestep_init
    public :: mmm_physics_compat_timestep_finalize
    public :: mmm_physics_accumulate_tendencies_timestep_init
    public :: mmm_physics_accumulate_tendencies_run
    public :: characteristic_grid_length_scale_init
    public :: geopotential_height_wrt_sfc_at_if_to_msl_run
    public :: geopotential_height_wrt_sfc_to_msl_run
contains
    !> \section arg_table_mmm_physics_compat_init Argument Table
    !! \htmlinclude mmm_physics_compat_init.html
    pure subroutine mmm_physics_compat_init( &
            theta_prev, qv_prev, &
            errmsg, errflg)
        use ccpp_kinds, only: kind_phys

        real(kind_phys), intent(out) :: theta_prev(:, :), qv_prev(:, :)
        character(*), intent(out) :: errmsg
        integer, intent(out) :: errflg

        errmsg = ''
        errflg = 0

        ! For remembering the states from the previous time step. They must be allocated at model initialization
        ! because they need to survive across time steps.
        theta_prev(:, :) = 0.0_kind_phys
        qv_prev(:, :) = 0.0_kind_phys
    end subroutine mmm_physics_compat_init

    !> \section arg_table_mmm_physics_compat_timestep_init Argument Table
    !! \htmlinclude mmm_physics_compat_timestep_init.html
    pure subroutine mmm_physics_compat_timestep_init( &
            theta_curr, theta_prev, qv_curr, qv_prev, dt, &
            rthdynten, rqvdynten, &
            errmsg, errflg)
        use ccpp_kinds, only: kind_phys

        real(kind_phys), intent(in) :: theta_curr(:, :), theta_prev(:, :), qv_curr(:, :), qv_prev(:, :), dt
        real(kind_phys), intent(out) :: rthdynten(:, :), rqvdynten(:, :)
        character(*), intent(out) :: errmsg
        integer, intent(out) :: errflg

        errmsg = ''
        errflg = 0

        rthdynten(:, :) = (theta_curr(:, :) - theta_prev(:, :)) / dt
        rqvdynten(:, :) = (qv_curr(:, :) - qv_prev(:, :)) / dt
    end subroutine mmm_physics_compat_timestep_init

    !> \section arg_table_mmm_physics_compat_timestep_finalize Argument Table
    !! \htmlinclude mmm_physics_compat_timestep_finalize.html
    pure subroutine mmm_physics_compat_timestep_finalize( &
            theta_curr, theta_prev, qv_curr, qv_prev, &
            errmsg, errflg)
        use ccpp_kinds, only: kind_phys

        real(kind_phys), intent(in) :: theta_curr(:, :), qv_curr(:, :)
        real(kind_phys), intent(out) :: theta_prev(:, :), qv_prev(:, :)
        character(*), intent(out) :: errmsg
        integer, intent(out) :: errflg

        errmsg = ''
        errflg = 0

        ! Remember the states at this time step. When the next time step comes, they will become
        ! the states from the previous one.
        theta_prev(:, :) = theta_curr(:, :)
        qv_prev(:, :) = qv_curr(:, :)
    end subroutine mmm_physics_compat_timestep_finalize

    !> \section arg_table_mmm_physics_accumulate_tendencies_timestep_init Argument Table
    !! \htmlinclude mmm_physics_accumulate_tendencies_timestep_init.html
    pure subroutine mmm_physics_accumulate_tendencies_timestep_init( &
            dudt, dvdt, &
            rublten, rvblten, &
            rthblten, rthratenlw, rthratensw, rqvblten, &
            errmsg, errflg)
        use ccpp_kinds, only: kind_phys

        real(kind_phys), intent(out) :: dudt(:, :), dvdt(:, :)
        real(kind_phys), intent(out) :: rublten(:, :), rvblten(:, :)
        real(kind_phys), intent(out) :: rthblten(:, :), rthratenlw(:, :), rthratensw(:, :), rqvblten(:, :)
        character(*), intent(out) :: errmsg
        integer, intent(out) :: errflg

        errmsg = ''
        errflg = 0

        ! Zero out tendencies at the beginning of each time step.

        ! Tendencies for feeding back to CAM-SIMA.
        dudt(:, :) = 0.0_kind_phys
        dvdt(:, :) = 0.0_kind_phys

        ! Tendencies generated by MMM physics.
        rublten(:, :) = 0.0_kind_phys
        rvblten(:, :) = 0.0_kind_phys
        rthblten(:, :) = 0.0_kind_phys
        rthratenlw(:, :) = 0.0_kind_phys
        rthratensw(:, :) = 0.0_kind_phys
        rqvblten(:, :) = 0.0_kind_phys
    end subroutine mmm_physics_accumulate_tendencies_timestep_init

    !> \section arg_table_mmm_physics_accumulate_tendencies_run Argument Table
    !! \htmlinclude mmm_physics_accumulate_tendencies_run.html
    pure subroutine mmm_physics_accumulate_tendencies_run( &
            dt, &
            dudt, dvdt, theta, qv, &
            rublten, rvblten, &
            rthblten, rthratenlw, rthratensw, rqvblten, &
            errmsg, errflg)
        use ccpp_kinds, only: kind_phys
        use ccpp_constituent_prop_mod, only: ccpp_constituent_prop_ptr_t

        real(kind_phys), intent(in) :: dt
        real(kind_phys), intent(inout) :: dudt(:, :), dvdt(:, :), theta(:, :), qv(:, :)
        real(kind_phys), intent(inout) :: rublten(:, :), rvblten(:, :)
        real(kind_phys), intent(inout) :: rthblten(:, :), rthratenlw(:, :), rthratensw(:, :), rqvblten(:, :)
        character(*), intent(out) :: errmsg
        integer, intent(out) :: errflg

        errmsg = ''
        errflg = 0

        ! Accumulate tendencies for feeding back to CAM-SIMA.
        dudt(:, :) = dudt(:, :) + rublten(:, :)
        dvdt(:, :) = dvdt(:, :) + rvblten(:, :)
        theta(:, :) = theta(:, :) + (rthblten(:, :) + rthratenlw(:, :) + rthratensw(:, :)) * dt
        qv(:, :) = qv(:, :) + rqvblten(:, :) * dt

        ! After the accumulation, zero out tendencies generated by MMM physics so that this subroutine is idempotent.
        rublten(:, :) = 0.0_kind_phys
        rvblten(:, :) = 0.0_kind_phys
        rthblten(:, :) = 0.0_kind_phys
        rthratenlw(:, :) = 0.0_kind_phys
        rthratensw(:, :) = 0.0_kind_phys
        rqvblten(:, :) = 0.0_kind_phys
    end subroutine mmm_physics_accumulate_tendencies_run

    !> \section arg_table_characteristic_grid_length_scale_init Argument Table
    !! \htmlinclude characteristic_grid_length_scale_init.html
    pure subroutine characteristic_grid_length_scale_init( &
            omega, rearth, dx, &
            errmsg, errflg)
        use ccpp_kinds, only: kind_phys

        real(kind_phys), intent(in) :: omega(:), rearth
        real(kind_phys), intent(out) :: dx(:)
        character(*), intent(out) :: errmsg
        integer, intent(out) :: errflg

        errmsg = ''
        errflg = 0

        ! These variables do not change with time. Set them just once at model initialization for better performance.

        ! Compute grid sizes in meters. This is trivial for models with regular grids like WRF,
        ! but not so straightforward for models with unstructured grids like CAM-SIMA. Here, the square root of cell area is used.
        dx(:) = sqrt(omega(:) * (rearth ** 2))
    end subroutine characteristic_grid_length_scale_init

    !> \section arg_table_geopotential_height_wrt_sfc_at_if_to_msl_run Argument Table
    !! \htmlinclude geopotential_height_wrt_sfc_at_if_to_msl_run.html
    pure subroutine geopotential_height_wrt_sfc_at_if_to_msl_run( &
            ncol, &
            gravit, phis, zisfc, &
            zimsl, &
            errmsg, errflg)
        use ccpp_kinds, only: kind_phys

        integer, intent(in) :: ncol
        real(kind_phys), intent(in) :: gravit, phis(:), zisfc(:, :)
        real(kind_phys), intent(out) :: zimsl(:, :)
        character(*), intent(out) :: errmsg
        integer, intent(out) :: errflg

        integer :: i

        errmsg = ''
        errflg = 0

        ! Convert geopotential height wrt surface at interface to geopotential height wrt mean sea level at interface,
        ! in accordance with its normal definition.
        do i = 1, ncol
            zimsl(i, :) = phis(i) / gravit + zisfc(i, :)
        end do
    end subroutine geopotential_height_wrt_sfc_at_if_to_msl_run

    !> \section arg_table_geopotential_height_wrt_sfc_to_msl_run Argument Table
    !! \htmlinclude geopotential_height_wrt_sfc_to_msl_run.html
    pure subroutine geopotential_height_wrt_sfc_to_msl_run( &
            ncol, &
            gravit, phis, zmsfc, &
            zmmsl, &
            errmsg, errflg)
        use ccpp_kinds, only: kind_phys

        integer, intent(in) :: ncol
        real(kind_phys), intent(in) :: gravit, phis(:), zmsfc(:, :)
        real(kind_phys), intent(out) :: zmmsl(:, :)
        character(*), intent(out) :: errmsg
        integer, intent(out) :: errflg

        integer :: i

        errmsg = ''
        errflg = 0

        ! Convert geopotential height wrt surface to geopotential height wrt mean sea level, in accordance with
        ! its normal definition.
        do i = 1, ncol
            zmmsl(i, :) = phis(i) / gravit + zmsfc(i, :)
        end do
    end subroutine geopotential_height_wrt_sfc_to_msl_run
end module mmm_physics_compat
